#自定义的配置放这里
druid-login:
  userName: ${druid_userName:root}
  password: ${druid_password:root}
  enable: ${druid_enable:true}
#  allow: 172.16.5.201,127.0.0.1
  allow: ${druid_allow:172.16.5.201}
http:
  ip: ${http_ip:172.16.16.104}
  port: ${http_port:31359}
  pageNumber: ${pageNumber:1}
  pageSize: ${pageSize:1000}
  header:
    tenantId: ${tenantId:1218734876489027584}
    grantId: ${grantId:1239814084715745280}
  orderProgress:
    formId: ${formId:1240468533985546242}
    condition: ${condition:{}}
  castOutput:
    formId: ${formId2:1240468533985546252}
#    condition: ${condition2:{}}
  coldRollOutput:
    formId: ${formId3:1240468533985546251}
#    condition: ${condition3:{}}
  wipParam:
    formId: ${formId4:1240468533985546249}