server:
  port: ${server_port:8080}

spring:
  #mongo配置
  data:
    mongodb:
      host: ${mongodb_host:172.16.16.71}
      port: ${mongodb_port:37017}
      username: ${mongodb_username:root}
      password: ${mongodb_password:123qweQWE,./}
      authentication-database: ${mongodb_authentication_database:admin}
      database: ${mongodb_database:form}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql_url:10.62.80.7}:${mysql_port:3306}/${mysql_database:test}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${mysql_username:root}
    password: ${mysql_password:root}
    type: com.alibaba.druid.pool.DruidDataSource

  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    serialization.write_dates_as_timestamps: true
    default-property-inclusion: non_null

logging:
  config: classpath:logback-spring.xml

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  type-aliases-package: cn.cncommdata.entity